import test from 'node:test'
import assert from 'node:assert/strict'
import {dubaiDay,monday,weeks,checkinState,validateContributions,resultValue} from './q4Cycle.js'
test('Dubai day and Monday rollover cross UTC safely',()=>{assert.equal(dubaiDay(new Date('2026-10-04T21:00:00Z')),'2026-10-05');assert.equal(monday('2026-10-03'),'2026-09-28');assert.equal(monday('2026-10-05'),'2026-10-05')})
test('quarter weeks include setup, exclude future weeks and stop at year end',()=>{assert.deepEqual(weeks('2026-10-03'),['2026-09-28']);assert.deepEqual(weeks('2026-10-05'),['2026-10-05','2026-09-28']);assert.equal(weeks('2027-02-01')[0],'2026-12-28');assert.equal(weeks('2027-02-01').length,14)})
test('unknown result is not a measured zero',()=>{assert.equal(resultValue({current_value:0,current_value_recorded_at:null,unit:'%'}),'Not measured');assert.equal(resultValue({current_value:0,current_value_recorded_at:'2026-10-03',unit:'%'}),'0%')})
test('UGC may draft without a supplied KR; submission requires link and milestones',()=>{const item={title:'Improve handoffs',done_when:'Review evidence',milestones:[]};assert.equal(validateContributions([item],'ugc',[],false),'');assert.notEqual(validateContributions([item],'ugc',[],true),'');assert.notEqual(validateContributions([item,item,item],'ugc',[],false),'')})
test('valid plan submits, invalid department link and date do not',()=>{const item={title:'Improve briefs',done_when:'Evidence reviewed',key_result_id:'kr',milestones:[{title:'Check findings',due_date:'2026-10-16'}]},results=[{id:'kr',objective_id:'cs'}];assert.equal(validateContributions([item],'cs',results,true),'');assert.notEqual(validateContributions([item],'ops',results,true),'');assert.notEqual(validateContributions([{...item,milestones:[{title:'Late',due_date:'2027-01-01'}]}],'cs',results,true),'')})
test('setup week is not flagged as overdue, submitted snapshot counts',()=>{const p={status:'draft',contributions:[{}]};assert.equal(checkinState(p,null,'2026-10-03'),'First review October 5');assert.equal(checkinState(p,null,'2026-10-05'),'Update due');assert.equal(checkinState(p,{locked_at:'2026-10-05'},'2026-10-05'),'Submitted')})
